name: Publish Docker Image

on:
  push:
    branches: [ main ]
  release:
    types:
      - published
        
jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"  #if the commit msg says to skip CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/Saman-Fatima/yocto-runner
          tag-sha: true
          tag-edge: false
          tag-latest: true
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
          
      - name: Build and push Docker image
        shell: bash
        run: |
          while read tag 
          do 
            docker build . -t $tag
            docker push $tag
          done <<< $(echo "${{ steps.meta.outputs.tags }}")
          
#       - name: Build image
#         uses: docker/build-push-action@v2
#         with:
#           tags: ${{ steps.docker_meta.outputs.tags }} # tags are coming from docker-meta job
#           file: ./Dockerfile
        
          
#       - name: Push image
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: ${{ steps.docker_meta.outputs.tags }}
#           file: ./Dockerfile

        
