name: On Pull Request
on:
 pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
    CONTAINER: "docker.github.vaillant-group.com/neext/plsw-linux-tools-yocto-build-container/plsw-linux-tools-yocto-build-container:latest"

jobs:
  call-commit-message-check:
    uses: NEEXT/plsw-linux-tools-shared-workflows/.github/workflows/shared-commit-message-check.yml@feature/change-on-pr-workflow
    secrets:
      machine-user: ${{ secrets.MACHINE_USER_NAME}}
      machine-user-token: ${{ secrets.MACHINE_USER_ACCESS_TOKEN }}
    with:
      container: $CONTAINER

